version: "3"
services:

  moodledb: # Banco de dados
    image: mysql
    container_name: moodledb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleadmin
      MYSQL_PASSWORD: moodle123123@
    volumes:
      - ./mysql_data/:/var/lib/mysql

  moodleapp: # Aplicação do Moodle
    image: bitnami/moodle
    container_name: moodleapp
    depends_on:
      - moodledb
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: moodledb
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodleadmin
      MOODLE_DATABASE_PASSWORD: moodle123123@
      MOODLE_SITE_NAME: OpenCodigo Academy
      MOODLE_LANG: pt_br
      MOODLE_USERNAME: leticia
      MOODLE_PASSWORD: le123123@
    ports:
      - "8080:8080"
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata 

volumes:
  mysql_data: 
  moodle_data: 