version: "3.9"
services:
  moodledb: # Banco de dados
    image: "mysql:${MOODLE_DOCKER_DB_VERSION:-8.0}"
    command: >
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_bin
            --skip-log-bin
    container_name: moodledb
    restart: always
    env_file: ".env"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleadmin
      MYSQL_PASSWORD: moodle123123@
    volumes:
      - "${MOODLE_DOCKER_VOLDB}:/var/lib/mysql"

  moodleapp: # Aplicação do Moodle
    image: "moodlehq/moodle-php-apache:${MOODLE_DOCKER_PHP_VERSION}"
    container_name: moodleapp
    depends_on:
      - moodledb
    restart: always
    env_file: ".env"
    environment: 
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_DBCOLLATION: utf8mb4_bin # utf8mb4: É a codificação de caracteres UTF-8 que suporta até 4 bytes por caractere
      MOODLE_DATABASE_HOST: moodledb
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodleadmin
      MOODLE_DATABASE_PASSWORD: moodle123123@  
    ports:
      - "${MOODLE_DOCKER_WEB_PORT}:80"
    volumes:
      - "${MOODLE_DOCKER_MOODLE}:/var/www/html"
      - "${MOODLE_DOCKER_MOODLEDATA}:/var/www/moodledata"
      - "${ASSETDIR}:/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf" 