version: "2"
services:
  moodledb:
    image: mysql:8.0
    command: >
                --character-set-server=utf8mb4
                --collation-server=utf8mb4_bin
                --skip-log-bin
    environment:
      MYSQL_ROOT_PASSWORD: "m@0dl3ing"
      MYSQL_USER: moodle
      MYSQL_PASSWORD: "m@0dl3ing"
      MYSQL_DATABASE: moodle
    volumes:
      - ./mysql_data/:/var/lib/mysql

  moodleapp:
    # apache com php e todas as estenções instaladas com sucesso
    image: moodlehq/moodle-php-apache:8.1
    container_name: moodleapp
    depends_on:
      - moodledb
    environment: 
      MOODLE_DOCKER_WEB_PORT: 8080
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: firefox
      # MOODLE_DOCKER_WEB_HOST:  
      MOODLE_DOCKER_DBTYPE: mysqli
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin # utf8mb4: É a codificação de caracteres UTF-8 que suporta até 4 bytes por caractere
    ports:
      - "8080:80"
    volumes:
      - ./moodle_code:/var/www/html
      - ./moodle_data:/var/www/moodledata
      - ./assets:/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf
    entrypoint: /bin/bash -c "chmod -R 777 /var/www/moodledata && docker-php-entrypoint apache2-foreground"

volumes:
  mysql_data:
  moodle_code:
  moodle_data:
