version: "3"
services:

  moodledb: # Banco de dados
    image: mysql
    # image: "mysql:${MOODLE_DOCKER_DB_VERSION:-8.0}"
    command: >
                --character-set-server=utf8mb4
                --collation-server=utf8mb4_bin
                --skip-log-bin
    container_name: moodledb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleadmin
      MYSQL_PASSWORD: moodle123123@
    volumes:
      - "${MOODLE_DOCKER_VOLDB}:/var/lib/mysql"

  moodleapp: # Aplicação do Moodle
    # apache com php e todas as estenções instaladas com sucesso
    image: "moodlehq/moodle-php-apache:${MOODLE_DOCKER_PHP_VERSION}" 
    container_name: moodleapp
    depends_on:
      - moodledb
    # restart: always
    # env_file: ".env"
    environment:
      MOODLE_DOCKER_WEB_PORT: 8080
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodleadmin
      MOODLE_DOCKER_DBPASS: "moodle123123@"
      MOODLE_DOCKER_BROWSER: firefox
      # MOODLE_DOCKER_WEB_HOST:  
      MOODLE_DOCKER_DBTYPE: mysqli
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin # utf8mb4: É a codificação de caracteres UTF-8 que suporta até 4 bytes por caractere
    ports:
      - "${MOODLE_DOCKER_WEB_PORT}:80"
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
      - "${MOODLE_DOCKER_MOODLEDATA}:/var/www/moodledata"
      - "${ASSETDIR}:/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf" 
    entrypoint: /bin/bash -c "chmod -R 777 /var/www/moodledata && docker-php-entrypoint apache2-foreground"


volumes:
  mysql_data:
  moodle_code:
  moodle_data: